app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:menu_id>', views.detail, name='detail'),
    path('new_menu', views.new_menu, name='new_menu'),
    path('delete_menu/<int:menu_id>', views.delete_menu, name='delete_menu'),
    path('edit_menu/<int:menu_id>', views.edit_menu, name='edit_menu'),
    path('weekly', views.weekly, name='weekly'),
]

menu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models

# Create your models here.
class Menu(models.Model):
    title = models.CharField(max_length=150)
    food_stuff = models.TextField(blank=True)
    name = models.TextField(blank=True)
    link = models.TextField(blank=True)
    text = models.TextField(blank=True)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

app/forms.py
from django.forms import ModelForm
from .models import Menu


class MenuForm(ModelForm):
	class Meta:
		model = Menu
		fields = ['title', 'food_stuff', 'name', 'link', 'text']

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Menu
from .forms import MenuForm
from django.views.decorators.http import require_POST
from django.db.models import Q

week_list = [['月','カレー'], ['火','焼きそば'], ['水','手巻き寿司']]

# Create your views here.
def index(request):
    menus = Menu.objects.all().order_by('id')
    return render(request, 'app/index.html', {'menus': menus})

def detail(request, menu_id):
  menu = get_object_or_404(Menu, id=menu_id)
  return render(request, 'app/detail.html', {'menu': menu})


def new_menu(request):
	if request.method == "POST":
		form = MenuForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('app:index')
	else:
		form = MenuForm
	return render(request, 'app/new_menu.html', {'form': form })

@require_POST
def delete_menu(request, menu_id):
	menu = get_object_or_404(Menu, id=menu_id)
	menu.delete()
	return redirect('app:index')

def edit_menu(request, menu_id):
    menu = get_object_or_404(Menu, id=menu_id)
    if request.method == "POST":
        form = MenuForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            return redirect('app:index')
    else:
        form = MenuForm(instance=menu)

    return render(request, 'app/edit_menu.html', {'form': form, 'menu':menu })


def weekly(request):
    if request.method == "POST":
        index = 0
        weekly = Menu.objects.all().order_by('?')[:3]

        for i in weekly:
            del week_list[index][1:]
            week_list[index].append(i.title)
            week_list[index].append(i.id)
            week_list[index].append(i.food_stuff)
            index += 1
    else:
        weekly = Menu.objects.all().filter(Q(title=week_list[2][1]) | Q(title=week_list[1][1]) | Q(title=week_list[0][1]))

    return render(request, 'app/weekly.html', {'weekly': weekly, 'week_list':week_list})

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <title>Weekly MainDish</title>
  <link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}">
</head>

<body>
  <h1>週間主菜（メインディッシュ）</h1>

  <div class="container">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

app/templates/app/detail.html
{% extends 'app/base.html' %}

{% block content %}

<div>
  <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>

<h2>{{ menu.title }}</h2>
<div>
  {{ menu.food_stuff | linebreaks | urlize }}
</div>
<div>
  {{ menu.text | linebreaks | urlize }}
</div>
<a href="{{ menu.link }}"  target="_blank">link</a>

<button><a class="btn" href="{% url 'app:edit_menu' menu.pk %}">編集</a></button>

<form method="post" action="{% url 'app:delete_menu' menu.pk %}">{% csrf_token %}
  <button class="btn" type="submit" onclick='return confirm("本当に削除しますか？");'>削除</button>
</form>
{% endblock %}

app/templates/app/edit_menu.html
{% extends 'app/base.html' %}

{% block content %}

<div>
  <a href="{% url 'app:detail' menu.id %}">戻る</a>
</div>

<form action="{% url 'app:edit_menu' menu.id %}" method="POST">{% csrf_token %}
  <table>
    <tr>
      <th>タイトル</th>
      <td>{{ form.title }}</td>
    </tr>
    <tr>
      <th>登録者名</th>
      <td>{{ form.name }}</td>
    </tr>
    <tr>
      <th>食材</th>
      <td>{{ form.food_stuff }}</td>
    </tr>
    <tr>
      <th>参考HP</th>
      <td>{{ form.link }}</td>
    </tr>
    <tr>
      <th>メモ</th>
      <td>{{ form.text }}</td>
    </tr>
  </table>
  <button class="btn" type="submit">保存</button>
</form>
{% endblock %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block content %}

<a class="btn" href="{% url 'app:new_menu' %}">新規メニュー登録</a>
<a class="btn" href="{% url 'app:weekly' %}">週間リスト</a>
{% for menu in menus %}

<a href="{% url 'app:detail' menu.id %}" class="menu-title">
  <div>
    {{ menu }}
    <span class="updated_datetime">{{ menu.name }}</span>
  </div>
</a>
{% endfor %}

{% endblock %}

app/templates/app/new_menu.html
{% extends 'app/base.html' %}

{% block content %}

<div>
  <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>

<form action="{% url 'app:new_menu'  %}" method="POST">{% csrf_token %}
  <table>
    <tr>
      <th>タイトル</th>
      <td>{{ form.title }}</td>
    </tr>
    <tr>
      <th>登録者名</th>
      <td>{{ form.name }}</td>
    </tr>
    <tr>
      <th>食材</th>
      <td>{{ form.food_stuff }}</td>
    </tr>
    <tr>
      <th>参考HP</th>
      <td>{{ form.link }}</td>
    </tr>
    <tr>
      <th>メモ</th>
      <td>{{ form.text }}</td>
    </tr>
  </table>
  <button class="btn" type="submit">保存</button>
</form>
{% endblock %}

app/templates/app/weekly.html
{% extends 'app/base.html' %}

{% block content %}

<div>
  <a href="{% url 'app:index' %}">ホームに戻る</a>
</div>
<form action="{% url 'app:weekly'  %}" method="POST">{% csrf_token %}
  <button class="btn" type="submit" onclick='return confirm("新しく献立を組み立てます");'>献立作成</button>
</form>

<div class="dow">
<span>{{week_list.0.0}}曜日</span>
<a href="{% url 'app:detail' week_list.0.2 %}" class="menu-title">
  {{ week_list.0.1 }}</a>
</div>
<div class="dow">
<span>{{week_list.1.0}}曜日</span>
<a href="{% url 'app:detail' week_list.1.2 %}" class="menu-title">
  {{ week_list.1.1 }}</a>
</div>
<div class="dow">
<span>{{week_list.2.0}}曜日</span>
<a href="{% url 'app:detail' week_list.2.2 %}" class="menu-title">
  {{ week_list.2.1 }}</a>
</div>
<div class="food_stuff_list">
  <p>お買い物リスト</p>
  <ul>
    <li>{{week_list.0.3}}</li>
    <li>{{week_list.1.3}}</li>
    <li>{{week_list.2.3}}</li>
  </ul>
</div>

{% endblock %}